apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
  namespace: devsecops-blue

spec:
  replicas: 2

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: frontend-blue

  template:
    metadata:
      labels:
        app: frontend-blue

    spec:
      containers:
        - name: frontend
          image: 124666675720.dkr.ecr.ap-south-1.amazonaws.com/devsecops-frontend:0fecf2b8d41851f9636a0ce5612fe820d17515f3

          ports:
            - containerPort: 80

          env:
            - name: USER_SERVICE_URL
              value: "http://user-service-blue.devsecops-blue.svc.cluster.local"

            - name: PRODUCT_SERVICE_URL
              value: "http://product-service-blue.devsecops-blue.svc.cluster.local"

            - name: ORDER_SERVICE_URL
              value: "http://order-service-blue.devsecops-blue.svc.cluster.local"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-blue
  namespace: devsecops-blue

spec:
  type: ClusterIP

  selector:
    app: frontend-blue

  ports:
    - port: 80
      targetPort: 80