apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-blue
  namespace: devsecops-blue

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: order-service-blue

  template:
    metadata:
      labels:
        app: order-service-blue

    spec:
      containers:
        - name: order-service
          image: 124666675720.dkr.ecr.ap-south-1.amazonaws.com/devsecops-order-service:0fecf2b8d41851f9636a0ce5612fe820d17515f3

          command:
            - java
          args:
            - "-javaagent:/otel/opentelemetry-javaagent.jar"
            - "-jar"
            - "/app/app.jar"

          ports:
            - containerPort: 8083

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          env:
            - name: OTEL_SERVICE_NAME
              value: order-service

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo.tempo.svc.cluster.local:4318

            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf

            - name: OTEL_TRACES_EXPORTER
              value: otlp

            - name: OTEL_METRICS_EXPORTER
              value: none

            - name: OTEL_LOGS_EXPORTER
              value: none

            - name: PRODUCT_SERVICE_URL
              value: http://product-service-blue.devsecops-blue.svc.cluster.local:8082

            # AWS Secrets Manager integration will replace
            # Kubernetes Secret references in the next step.

---
apiVersion: v1
kind: Service
metadata:
  name: order-service-blue
  namespace: devsecops-blue

spec:
  type: ClusterIP

  selector:
    app: order-service-blue

  ports:
    - name: http
      port: 8083
      targetPort: 8083
