apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: devsecops-mysql-secrets
  namespace: devsecops-green

spec:
  provider: aws

  parameters:
    region: ap-south-1
    usePodIdentity: "true"

    objects: |
      - objectName: "devsecops/mysql"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: mysql-username
            filePermission: "0400"
          - path: password
            objectAlias: mysql-password
            filePermission: "0400"

  secretObjects:
    - secretName: devsecops-mysql
      type: Opaque
      data:
        - objectName: mysql-username
          key: username
        - objectName: mysql-password
          key: password