
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: frontend-blue-tgc
  namespace: devsecops-blue
spec:
  targetReference:
    name: frontend-blue
  defaultConfiguration:
    targetType: ip
    healthCheckConfig:
      healthCheckPath: /
      healthCheckPort: "80"
      healthCheckProtocol: http
      matcher:
        httpCode: "200-399"
---
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: frontend-green-tgc
  namespace: devsecops-green
spec:
  targetReference:
    name: frontend-green
  defaultConfiguration:
    targetType: ip
    healthCheckConfig:
      healthCheckPath: /
      healthCheckPort: "80"
      healthCheckProtocol: http
      matcher:
        httpCode: "200-399"
---

apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: user-blue-tgc
  namespace: devsecops-blue
spec:
  targetReference:
    name: user-service-blue
  defaultConfiguration:
    targetType: ip
    healthCheckConfig:
      healthCheckPath: /actuator/health
      healthCheckPort: "8081"
      healthCheckProtocol: http
      matcher:
        httpCode: "200-399"
---

apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: user-green-tgc
  namespace: devsecops-green
spec:
  targetReference:
    name: user-service-green
  defaultConfiguration:
    targetType: ip
    healthCheckConfig:
      healthCheckPath: /actuator/health
      healthCheckPort: "8081"
      healthCheckProtocol: http
      matcher:
        httpCode: "200-399"
---



apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: product-blue-tgc
  namespace: devsecops-blue
spec:
  targetReference:
    name: product-service-blue
  defaultConfiguration:
    targetType: ip
    healthCheckConfig:
      healthCheckPath: /actuator/health
      healthCheckPort: "8082"
      healthCheckProtocol: http
      matcher:
        httpCode: "200-399"

---
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: product-green-tgc
  namespace: devsecops-green
spec:
  targetReference:
    name: product-service-green
  defaultConfiguration:
    targetType: ip
    healthCheckConfig:
      healthCheckPath: /actuator/health
      healthCheckPort: "8082"
      healthCheckProtocol: http
      matcher:
        httpCode: "200-399"

---

apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: order-blue-tgc
  namespace: devsecops-blue
spec:
  targetReference:
    name: order-service-blue
  defaultConfiguration:
    targetType: ip
    healthCheckConfig:
      healthCheckPath: /actuator/health
      healthCheckPort: "8083"
      healthCheckProtocol: http
      matcher:
        httpCode: "200-399"

---
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: order-green-tgc
  namespace: devsecops-green
spec:
  targetReference:
    name: order-service-green
  defaultConfiguration:
    targetType: ip
    healthCheckConfig:
      healthCheckPath: /actuator/health
      healthCheckPort: "8083"
      healthCheckProtocol: http
      matcher:
        httpCode: "200-399"